### ISSUE TITLE
Cannot start applet 

### ISSUE THREAD

**Issue by oandros1** [fornwall/eclipsecoder#9]
I cannot start applet from eclipse luna, java 8 win 8, i'm having
java.lang.reflect.InvocationTargetException

!ENTRY net.fornwall.eclipsecoder 4 0 2015-11-14 21:09:47.959
!MESSAGE java.lang.reflect.InvocationTargetException
!STACK 0
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fornwall.eclipsecoder.actions.TopCoderAppletLauncher.startContestAppletFirstTime(TopCoderAppletLauncher.java:254)
    at net.fornwall.eclipsecoder.actions.TopCoderAppletLauncher.run(TopCoderAppletLauncher.java:114)
    at net.fornwall.eclipsecoder.actions.LaunchTopCoderAppletJob.run(LaunchTopCoderAppletJob.java:172)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.NoClassDefFoundError: com/topcoder/netCommon/contestantMessages/response/VoteResponse
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
    at java.lang.Class.getDeclaredMethod(Unknown Source)
    at java.awt.Component.isCoalesceEventsOverriden(Unknown Source)
    at java.awt.Component.access$500(Unknown Source)
    at java.awt.Component$3.run(Unknown Source)
    at java.awt.Component$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.Component.checkCoalescing(Unknown Source)
    at java.awt.Component.<init>(Unknown Source)
    at java.awt.Container.<init>(Unknown Source)
    at java.awt.Panel.<init>(Unknown Source)
    at java.awt.Panel.<init>(Unknown Source)
    at java.applet.Applet.<init>(Unknown Source)
    at javax.swing.JApplet.<init>(Unknown Source)
    at com.topcoder.client.contestApplet.ContestApplet.<init>(Unknown Source)
    at com.topcoder.client.contestApplet.runner.generic.main(Unknown Source)
    ... 8 more
Caused by: java.lang.ClassNotFoundException: com.topcoder.netCommon.contestantMessages.response.VoteResponse
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 25 more
Root exception:
java.lang.NoClassDefFoundError: com/topcoder/netCommon/contestantMessages/response/VoteResponse
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
    at java.lang.Class.getDeclaredMethod(Unknown Source)
    at java.awt.Component.isCoalesceEventsOverriden(Unknown Source)
    at java.awt.Component.access$500(Unknown Source)
    at java.awt.Component$3.run(Unknown Source)
    at java.awt.Component$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.awt.Component.checkCoalescing(Unknown Source)
    at java.awt.Component.<init>(Unknown Source)
    at java.awt.Container.<init>(Unknown Source)
    at java.awt.Panel.<init>(Unknown Source)
    at java.awt.Panel.<init>(Unknown Source)
    at java.applet.Applet.<init>(Unknown Source)
    at javax.swing.JApplet.<init>(Unknown Source)
    at com.topcoder.client.contestApplet.ContestApplet.<init>(Unknown Source)
    at com.topcoder.client.contestApplet.runner.generic.main(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fornwall.eclipsecoder.actions.TopCoderAppletLauncher.startContestAppletFirstTime(TopCoderAppletLauncher.java:254)
    at net.fornwall.eclipsecoder.actions.TopCoderAppletLauncher.run(TopCoderAppletLauncher.java:114)
    at net.fornwall.eclipsecoder.actions.LaunchTopCoderAppletJob.run(LaunchTopCoderAppletJob.java:172)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.ClassNotFoundException: com.topcoder.netCommon.contestantMessages.response.VoteResponse
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 25 more

**Comment by fornwall** [comment]
Do you still have this problem? Which eclipse version are you running?

**Comment by oandros1** [comment]
Hello,

Thank you for your email.

yes, I'm still having a problem with launching eclipsecoder. I'm using
Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600

if you could help me it would be great!

Thank you,
Oleg
